/**
 * The reserved names of the Python translator (docs/PYTHON.md §2.14, §10.2): what a Python name
 * cannot be called in the generated sketch. src/python/reserved-names.ts is generated by
 * scripts/gen-reserved-names.mjs with the WebAssembly avr-g++ of the Upload feature; where that
 * toolchain is present, the committed file must be what the script makes today.
 */
import { describe, expect, it } from 'vitest';
import { execFileSync } from 'node:child_process';
import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { RESERVED_NAMES } from '../src/python/reserved-names';
import { PINS } from '../src/sketch/pins';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const hasToolchain = existsSync(`${ROOT}public/toolchain/tools/cc1plus.wasm`) && existsSync(`${ROOT}public/toolchain/bundle/manifest.json`);

describe('RESERVED_NAMES', () => {
  it('has the C++ keywords and alternative tokens', () => {
    for (const name of ['int', 'long', 'class', 'new', 'delete', 'this', 'template', 'auto', 'register', 'switch', 'case', 'default', 'do', 'goto', 'nullptr', 'char16_t']) {
      expect(RESERVED_NAMES.has(name), name).toBe(true);
    }
    for (const name of ['and', 'and_eq', 'bitand', 'bitor', 'compl', 'not', 'not_eq', 'or', 'or_eq', 'xor', 'xor_eq']) expect(RESERVED_NAMES.has(name), name).toBe(true);
  });
  it('has every binary constant B0 … B11111111 of binary.h', () => {
    let count = 0;
    for (let bits = 1; bits <= 8; bits++) {
      for (let value = 0; value < 2 ** bits; value++) {
        const name = `B${value.toString(2).padStart(bits, '0')}`;
        expect(RESERVED_NAMES.has(name), name).toBe(true);
        count++;
      }
    }
    expect(count).toBe(510);
  });
  it('has the Arduino macros and the names whose declaration fails in a sketch', () => {
    for (const name of ['abs', 'min', 'max', 'round', 'sq', 'constrain', 'F', 'DEFAULT', 'HIGH', 'LOW', 'PI', 'EULER', 'INPUT', 'OUTPUT', 'A0', 'A5', 'LED_BUILTIN', 'PORTB', 'ADC']) {
      expect(RESERVED_NAMES.has(name), name).toBe(true);
    }
    for (const name of ['square', 'rand', 'div', 'exp', 'log', 'map', 'random', 'delay', 'millis', 'tone', 'setup', 'loop', 'Serial', 'Wire', 'String', 'DHT22', 'uint8_t', 'size_t']) {
      expect(RESERVED_NAMES.has(name), name).toBe(true);
    }
  });
  it('has the names the translator emits', () => {
    for (const name of ['main', 'byte', 'word', 'boolean', 'pyFail', 'pyFloorDiv', 'pyMod', 'pyNonZero', 'pyPow', 'pyFloat', 'pyPad', 'pyIndex', 'pyDistanceCm']) expect(RESERVED_NAMES.has(name), name).toBe(true);
    for (const base of ['pyAppend', 'pyPop', 'pyListText', 'pySum', 'pyMinList', 'pyMaxList', 'pyInList']) {
      for (const kind of ['L', 'F', 'S', 'B']) expect(RESERVED_NAMES.has(base + kind), base + kind).toBe(true);
    }
    for (const name of ['showSegments', 'showDigit', 'Servo', 'LiquidCrystal_I2C', 'DHT', 'Adafruit_NeoPixel', ...PINS.map((p) => p.name)]) expect(RESERVED_NAMES.has(name), name).toBe(true);
  });
  it('keeps everyday names free (parameter names of the library headers do not leak in)', () => {
    for (const name of ['value', 'count', 'data', 'x', 'y', 'i', 'n', 'led', 'button', 'total', 'name', 'text', 'speed', 'distance', 'angle', 'temperature', 'time', 'index', 'result', 'size', 'buffer', 'pin', 'answer', 'readings']) {
      expect(RESERVED_NAMES.has(name), name).toBe(false);
    }
  });
});

describe.skipIf(!hasToolchain)('scripts/gen-reserved-names.mjs', () => {
  it('the committed file is what the script makes with the toolchain', () => {
    expect(() => execFileSync('node', ['scripts/gen-reserved-names.mjs', '--check'], { cwd: ROOT, stdio: 'pipe' })).not.toThrow();
  }, 60_000);
});
